#!/bin/bash

# check for env var HOME or assume /home/USER
if [ "$HOME" ]
then
	home="$HOME"
else
	home="/home/`whoami`/"
fi
zshrc="$home/.zshrc"
exists=false

# in the right folder?
if [ ! -f "zshrc" ] && [ ! -d ".git" ]
then
	echo "Please change to the dir the 'link' exists."
	exit 1
elif [ -h "$(pwd)" ]
then
	echo "You are in an already symlinked directory. Change to real dir."
	echo "Real dir: $(stat -c %N `pwd` | awk -F\` '{print $3}' | sed "s/'//g") ."
	exit 1
elif [ -d "$home/.zsh" ]
then
	exists="true"
fi

# backup if file exists or unlink it
if [ -h "$zshrc" ]
then
	unlink ~/.zshrc && echo ".zshrc is now unlinked."
else
	mv ~/.zshrc ~/.zshrc.bak && echo ".zshrc backed up."
fi

# link it
ln -s `pwd`/zshrc ~/.zshrc && echo ".zshrc is now linked."

# assume link already exists
if [ "$exists" == "false" ]
then
	ln -s `pwd` "$home"/.zsh 2> /dev/null || unlink "$home"/.zsh 2> /dev/null && ln -s `pwd` "$home"/.zsh 2> /dev/null
	if [ -h "$home/.zsh" ]
	then 
		echo "successfully linked dir to '$home/.zsh'."
	else 
		echo "symlinking failed, sorry :("
	fi
fi

echo "now updating and initiating submodule"
git submodule init
git submodule update
