#!/bin/bash

# check for env var HOME or assume /home/USER
if [ "$HOME" ]
then
	home="$HOME"
else
	home="/home/`whoami`/"
fi
zshrc="$home/.zshrc"

# in the right folder?
if [ ! -f "zshrc" ] && [ ! -d ".git" ]
then
	echo "Please change to the dir the 'link' exists."
	exit 1
elif [ -h "$(pwd)" ]
then
	echo "You are in an already symlinked directory. Change to real dir."
	exit 1
elif [ -d "$home/.zsh" ]
then
	echo "Directory '$home/.zsh' already exists. Please move the content away so this script works."
	exit 1
fi

# backup if file exists or unlink it
if [ -h "$zshrc" ]
then
	unlink ~/.zshrc && echo ".zshrc is now unlinked."
else
	mv ~/.zshrc ~/.zshrc.bak && echo ".zshrc backed up."
fi

# link it
ln -s `pwd`/zshrc ~/.zshrc && echo ".zshrc is now linked."

# assume link already exists
ln -s `pwd` "$home"/.zsh/ 2> /dev/null || unlink "$home"/.zsh/ 2> /dev/null && ln -s `pwd` "$home"/.zsh/ 2> /dev/null
