#!/bin/bash

# in the right folder?
if [ ! -f "zshrc" ]
then
	echo "Please change to the dir the 'link' exists."
	exit 1
fi

# backup
if [ -a ~/.zshrc ]
then
	mv ~/.zshrc ~/.zshrc.bak
fi

# link it
ln -s `pwd`/zshrc ~/.zshrc
